=== kcelia/M1/MLBDA/tds/dtd1/restaurant.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT restaurant ( nom , fermeture,ville , etoile, menus ) >
<!ELEMENT nom (#CPDATA) >
<!ELEMENT fermeture (#CPDATA) >
<!ELEMENT ville ( nom, departement,monument )>
<!ELEMENT departement (#PCDATA)>
<!ELEMENT monument (nom,tarif)>
<!ELEMENT tarif (#PCDATA)>
<!ELEMENT etoile (#PCDATA) >
<!ELEMNT menus(menu+)>  
<!ELEMENT menu (nom, prix)>
<!ELEMENT prix (#PCDATA)>

=== kcelia/M1/MLBDA/tds/dtd1/restaurant.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE restaurant SYSTEM "restaurant.dtd">



<restaurant>
	<nom>la tour d'argent</nom>
	<fermture>dimanche et lundi</fermeture>
	<ville>
		<nom>paris</nom>
		<departement>75</departement>
		<monument>
		<nom>Le Louvre</nom>
		<tarif>8</tarif>
		</monument>
	</ville>
	<etoile>2</etoile>
	<menus>
		<menu>
			<nom>buffet</nom>
			<prix>200</prix>
		</menu>
		<menu>
			<nom>gourmet</nom>
			<prix>300</prix>
		</menu>
	<menus>
	
</restaurant>
