=== kcelia/M1/MLBDA/tds/dtd/restaurant.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ELEMENT restaurant (nom, ville, fermeture, etoile, menus)>
<!ELEMENT nom (#PCDATA)>
<!ELEMENT fermeture (#PCDATA)>
<!ELEMENT etoile (#PCDATA)>
<!ELEMENT ville (nom, departement, monument)>
<!ELEMENT departement (#PCDATA)>
<!ELEMENT monument (nom, tarif)>
<!ELEMENT tarif (#PCDATA)>
<!ELEMENT menus (menu+)>
<!ELEMENT menu (nom, prix)>
<!ELEMENT prix (#PCDATA)>

=== kcelia/M1/MLBDA/tds/dtd/restaurant.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE restaurant SYSTEM "restaurant.dtd">

<restaurant>
	<nom>restaurant_universitaire</nom>
	<ville>
		<nom>PARIS</nom>
		<departement>PARIS</departement>
		<monument>
			<nom>Louvre</nom>
			<tarif>8eur</tarif>
		</monument>
	</ville>
	<fermeture>week-end</fermeture>
	<etoile>0</etoile>
	<menus>
		<menu>
			<nom>unique</nom>
			<prix>2eur</prix>
		</menu>
	</menus>
</restaurant>
